# Generated by Django 3.0.6 on 2020-05-28 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('license_plate', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('run', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=45)),
                ('category', models.CharField(choices=[('A', 'Motorcycle'), ('B', 'Car'), ('C', 'Truck'), ('D', 'Bus'), ('M', 'Moped')], default='B', max_length=1)),
                ('experience', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Manifests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Cars')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Model_of_car',
            fields=[
                ('model', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=45)),
                ('carrying', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('From client', 'From client'), ('To client', 'To client')], default='From client', max_length=11)),
                ('kilometrage', models.FloatField()),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
                ('second_point', models.CharField(max_length=45)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Clients')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Manifests')),
            ],
        ),
        migrations.CreateModel(
            name='Order_composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Orders')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopark.Model_of_car'),
        ),
    ]
