# Generated by Django 3.0.5 on 2020-04-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('category', models.CharField(choices=[('A', 'Мотоциклы'), ('A1', 'Легкие мотоциклы'), ('B', 'Легковые автомобили, небольшие грузовики (до 3,5 тонн)'), ('BE', 'Легковые автомобили с прицепом'), ('B1', 'Трициклы'), ('C', 'Грузовые автомобили (от 3,5 тонн)'), ('CE', 'Грузовые автомобили с прицепом'), ('C1', 'Средние грузовики (от 3,5 до 7,5 тонн)'), ('C1E', 'Средние грузовики с прицепом'), ('D', 'Автобусы'), ('DE', 'Автобусы с прицепом'), ('D1', 'Небольшие автобусы'), ('D1E', 'Небольшие автобусы с прицепом'), ('M', 'Мопеды'), ('Tm', 'Трамваи'), ('Tb', 'Троллейбусы')], max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner')),
            ],
        ),
    ]
