# Generated by Django 3.1 on 2020-10-27 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Factory', 'Factory'), ('Studio', 'Studio'), ('Person', 'Person')], max_length=50)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Fur',
            fields=[
                ('fur_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sort', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farm')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
                ('fur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fur')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
