# Generated by Django 3.1 on 2020-10-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
