# Generated by Django 3.0.8 on 2020-07-05 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_number', models.IntegerField()),
                ('price_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name_captain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateField()),
                ('date_of_arrival', models.DateField()),
                ('quantity_post_of_1', models.IntegerField()),
                ('quantity_post_of_2', models.IntegerField()),
                ('quantity_post_of_3', models.IntegerField()),
                ('information', models.TextField()),
                ('photo', models.TextField()),
                ('id_cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Excursion')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
    ]
