# Generated by Django 3.0.8 on 2020-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='id_cruise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='id_excursion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='id_profile',
            field=models.IntegerField(),
        ),
    ]
