# Generated by Django 3.0.4 on 2020-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_remove_car_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Car',
            field=models.ManyToManyField(through='project_first_app.Owner', to='project_first_app.Car'),
        ),
    ]
