# Generated by Django 3.0.4 on 2020-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_person_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Car',
        ),
        migrations.AddField(
            model_name='car',
            name='Car',
            field=models.ManyToManyField(through='project_first_app.Owner', to='project_first_app.Person'),
        ),
    ]
