# Generated by Django 3.0.7 on 2020-10-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client name'),
            preserve_default=False,
        ),
    ]
