# Generated by Django 3.0.7 on 2020-06-30 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportproj', '0002_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 30)),
        ),
    ]
