# Generated by Django 3.0.5 on 2020-06-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200618_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
