# Generated by Django 3.0.5 on 2020-06-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
