# Generated by Django 3.0.5 on 2020-06-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200623_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='core.Board'),
        ),
    ]
