# Generated by Django 3.0.5 on 2020-06-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200623_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='core.Panel'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='core.Board'),
        ),
    ]
