# Generated by Django 3.0.3 on 2020-03-12 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='driver_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField(max_length=10)),
                ('license_type', models.CharField(max_length=30)),
                ('license_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Indefinite')], max_length=1)),
                ('passport_ID', models.IntegerField(max_length=10)),
                ('license_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levashova_app.driver_license')),
            ],
        ),
        migrations.CreateModel(
            name='Car_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.DateField()),
                ('sale', models.DateField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levashova_app.Car')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Levashova_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='cars',
            field=models.ManyToManyField(through='Levashova_app.Car_User', to='Levashova_app.User'),
        ),
    ]
