# Generated by Django 3.0.6 on 2020-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_auto_20200623_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
