# Generated by Django 3.0.6 on 2020-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_auto_20200623_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
