# Generated by Django 3.1.2 on 2020-10-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brandlist',
            fields=[
                ('brandlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
            ],
            options={
                'db_table': 'brandlist',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=100)),
                ('gov_number', models.CharField(max_length=100)),
                ('brand_id', models.IntegerField()),
                ('car_year', models.DateField()),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_id', models.IntegerField()),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('masterlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_id', models.IntegerField()),
                ('master_id', models.IntegerField()),
            ],
            options={
                'db_table': 'masterlist',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('master_id', models.AutoField(primary_key=True, serialize=False)),
                ('master_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('worktype_id', models.AutoField(primary_key=True, serialize=False)),
                ('worktype_name', models.CharField(max_length=100)),
                ('worktype_price', models.IntegerField()),
            ],
            options={
                'db_table': 'pricelist',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_arrival', models.DateField()),
                ('date_done', models.DateField()),
                ('worktype_id', models.IntegerField()),
                ('masterlist_id', models.IntegerField()),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'workshops',
            },
        ),
        migrations.CreateModel(
            name='Workslist',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
            ],
            options={
                'db_table': 'workslist',
            },
        ),
    ]
