# Generated by Django 3.1.2 on 2020-10-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshow', '0002_delete_brandlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brandlist',
            fields=[
                ('brandlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
            ],
            options={
                'db_table': 'brandlist',
            },
        ),
    ]
