# Generated by Django 3.1.2 on 2020-11-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoshow', '0005_brandlist_brands_cars_documents_masterlist_masters_pricelist_works_workshops_workslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandlist',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='brandlist',
            name='workshop_id',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='master_id',
        ),
        migrations.RemoveField(
            model_name='masterlist',
            name='workshop_id',
        ),
        migrations.RemoveField(
            model_name='works',
            name='masterlist_id',
        ),
        migrations.RemoveField(
            model_name='works',
            name='worktype_id',
        ),
        migrations.RemoveField(
            model_name='workslist',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='workslist',
            name='work_id',
        ),
        migrations.AddField(
            model_name='brandlist',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandlist',
            name='workshop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.workshops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.cars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterlist',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.masters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterlist',
            name='workshop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.workshops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='masterlist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.masterlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='workshop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.workshops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workslist',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workslist',
            name='work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autoshow.works'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gov_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='owner_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masters',
            name='master_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='worktype_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='date_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='date_done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='workshop_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
