# Generated by Django 3.1.2 on 2020-11-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshow', '0007_auto_20201101_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
