# Generated by Django 3.1.2 on 2020-11-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoshow', '0008_workshops_workshop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='workshop',
        ),
        migrations.AddField(
            model_name='works',
            name='worktype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='autoshow.pricelist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='worktype_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
