# Generated by Django 3.1.2 on 2020-11-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoshow', '0009_auto_20201101_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='worktype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoshow.pricelist'),
        ),
    ]
