# Generated by Django 3.0.5 on 2020-04-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdoc',
            name='type',
            field=models.CharField(choices=[('M', 'Minivan'), ('S', 'Super car'), ('R', 'Roadster'), ('L', 'Limousine')], max_length=30),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('cars', models.ManyToManyField(through='project_first_app.Ownership', to='project_first_app.Auto')),
            ],
        ),
        migrations.AlterField(
            model_name='driverdoc',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Owner'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
