# Generated by Django 3.0.4 on 2020-04-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
