# Generated by Django 3.1.1 on 2020-09-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('state_number', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('secondName', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Owning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBuy', models.DateField()),
                ('dateSell', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhilina_app.auto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhilina_app.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='autos',
            field=models.ManyToManyField(through='zhilina_app.Owning', to='zhilina_app.Auto'),
        ),
        migrations.CreateModel(
            name='DriveLic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('R', 'Russia'), ('I', 'International')], max_length=1)),
                ('dateIssued', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhilina_app.owner')),
            ],
        ),
    ]
