# Generated by Django 3.0.7 on 2020-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0002_auto_20200625_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockey',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jockey',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jockey',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
