# Generated by Django 3.0.7 on 2020-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0003_auto_20200625_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockey',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
