# Generated by Django 3.0.7 on 2020-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0004_auto_20200625_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='jockey',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
