# Generated by Django 3.0.7 on 2020-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0005_jockey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='image',
            field=models.ImageField(default='default_horse.jpg', upload_to='horse_pics'),
        ),
        migrations.AlterField(
            model_name='jockey',
            name='image',
            field=models.ImageField(default='default_user.jpg', upload_to='profile_pics'),
        ),
    ]
