# Generated by Django 3.0.7 on 2020-06-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0006_auto_20200625_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jockey',
            name='surname',
        ),
    ]
