# Generated by Django 3.0.8 on 2020-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0007_remove_jockey_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='image',
        ),
        migrations.AlterField(
            model_name='race',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
