# Generated by Django 3.0.7 on 2020-07-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_auto_20200621_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сassette',
            name='duration',
        ),
    ]
