# Generated by Django 3.0.7 on 2020-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kugachFinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
