# Generated by Django 3.0.4 on 2020-04-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_person_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cars',
            field=models.ManyToManyField(to='project_first_app.Auto'),
        ),
    ]
