# Generated by Django 3.0.4 on 2020-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0004_auto_20200415_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='data_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='data_start',
            field=models.DateField(blank=True),
        ),
    ]
