# Generated by Django 3.0.4 on 2020-03-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('development_Year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Obtaining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_date', models.DateField()),
                ('Auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chervyakov_app.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('passport', models.IntegerField(max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('I', 'I dont wanna tell you')], max_length=1)),
                ('obt', models.ManyToManyField(through='Chervyakov_app.Obtaining', to='Chervyakov_app.Auto')),
            ],
        ),
        migrations.AddField(
            model_name='obtaining',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chervyakov_app.Person'),
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(max_length=8)),
                ('privalages', models.CharField(choices=[('Rg', 'Regional'), ('WW', 'World')], max_length=9)),
                ('Date_of_obtaining', models.DateField()),
                ('ForKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chervyakov_app.Person')),
            ],
        ),
    ]
