# Generated by Django 3.0.4 on 2020-03-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chervyakov_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='development_Year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='licence',
            name='Number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.CharField(max_length=10),
        ),
    ]
