# Generated by Django 3.1.2 on 2020-10-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_lab', '0002_auto_20201013_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='Number',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Номер автобуса'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Name_route', to='final_lab.routes', verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_bus', to='final_lab.buses', verbose_name='Номер автобуса'),
        ),
        migrations.AlterField(
            model_name='ways',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='final_lab.routes', verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='ways',
            name='Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number', to='final_lab.buses', verbose_name='Номер автобуса'),
        ),
    ]
