# Generated by Django 3.1.2 on 2020-10-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_lab', '0003_auto_20201013_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Number',
            new_name='Number_b',
        ),
    ]
