# Generated by Django 3.1.2 on 2020-10-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_lab', '0005_auto_20201013_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Birth_year',
            field=models.DateField(max_length=4, verbose_name='Дата рождения'),
        ),
    ]
