# Generated by Django 3.0.3 on 2020-03-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=15)),
                ('date_getting', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender_ch', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], max_length=1)),
                ('passport_id', models.IntegerField(max_length=10)),
                ('drive_license_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ivakhniuk_app.DriverLicense')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField()),
                ('buy_date', models.DateField()),
                ('Auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ivakhniuk_app.Auto')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ivakhniuk_app.User')),
            ],
        ),
    ]
