# Generated by Django 3.0.3 on 2020-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ivakhniuk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='driving',
            field=models.ManyToManyField(through='Ivakhniuk_app.Usage', to='Ivakhniuk_app.User'),
        ),
    ]
