# Generated by Django 3.1.2 on 2020-10-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=30)),
                ('name_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30)),
                ('number_passport_customer', models.BigIntegerField()),
                ('number_phone_cus', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('name_hotel', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Nomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfNomer', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateField()),
                ('date_exit', models.DateField()),
                ('status_nomer', models.CharField(choices=[('b', 'Busy'), ('f', 'Free'), ('z', 'Booked')], max_length=1)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.customers')),
                ('nomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.nomer')),
            ],
        ),
        migrations.CreateModel(
            name='InfoAboutNomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('count_customers', models.IntegerField()),
                ('type_nomer', models.CharField(choices=[('s', 'Standart'), ('p', 'President'), ('e', 'Econom'), ('l', 'Lux')], max_length=1)),
                ('nomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.nomer')),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='nomer',
            field=models.ManyToManyField(through='mainApp.Registration', to='mainApp.Nomer'),
        ),
    ]
