# Generated by Django 3.1.2 on 2020-10-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoaboutnomer',
            name='nomer',
        ),
        migrations.AddField(
            model_name='nomer',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.infoaboutnomer'),
            preserve_default=False,
        ),
    ]
