# Generated by Django 3.0.10 on 2020-10-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('mileage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion_route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('start_location', models.CharField(max_length=45, verbose_name='start_location')),
                ('end_location', models.CharField(max_length=45, verbose_name='end_location')),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Crew_member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('second_name', models.CharField(max_length=45, verbose_name='second_name')),
                ('exp', models.IntegerField()),
                ('category', models.IntegerField()),
                ('adress', models.CharField(max_length=45, verbose_name='adress')),
                ('birth_year', models.IntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_buro.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Completed_trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('n_passengers', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_buro.Bus')),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_buro.Excursion_route')),
            ],
        ),
    ]
