# Generated by Django 3.0.3 on 2020-06-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Скидка за показ')),
                ('advertiser_name', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время выхода в эфир')),
                ('cost', models.FloatField(verbose_name='Стоимость показа за минуту')),
                ('show_name', models.CharField(max_length=45, verbose_name='Название')),
                ('idChannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adApp.Channel', verbose_name='Номер канала')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adName', models.CharField(max_length=45, verbose_name='Название')),
                ('time', models.IntegerField(verbose_name='Время ролика')),
                ('idAdvertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adApp.Advertiser', verbose_name='Рекламная компания')),
            ],
            options={
                'verbose_name': 'Ролик',
                'verbose_name_plural': 'Ролики',
            },
        ),
        migrations.CreateModel(
            name='AdBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата показа')),
                ('idAdvertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adApp.Advertising', verbose_name='Ролик')),
                ('idTVShow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adApp.TVShow', verbose_name='ТВ программа')),
            ],
            options={
                'verbose_name': 'Показ ролика',
                'verbose_name_plural': 'Показы ролика',
            },
        ),
    ]
