# Generated by Django 3.1.1 on 2020-10-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ruble', 'Ruble'), ('Belarusian ruble', 'Belarusian ruble'), ('Euro', 'Euro'), ('Dollar', 'Dollar'), ('Hryvnia', 'Hryvnia')], max_length=30)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('passportID', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('phoneNumber', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('profession', models.CharField(choices=[('Administrator', 'Administrator'), ('Operator', 'Operator'), ('Director', 'Director'), ('Support', 'Support')], max_length=30, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('min_date', models.IntegerField(verbose_name='Минимальный срок')),
                ('min_sum', models.IntegerField(verbose_name='Минимальная сумма')),
                ('percent', models.FloatField(verbose_name='Процент в месяц')),
                ('currency_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.currency')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField(auto_now_add=True, verbose_name='Дата вклада')),
                ('refund_date', models.DateField(verbose_name='Дата возврата')),
                ('depositAmount', models.FloatField(verbose_name='Сумма вклада')),
                ('refundAmount', models.FloatField(verbose_name='Сумма возврата')),
                ('deposit_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.deposit')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.employee')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('age', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('account', models.ManyToManyField(to='bank.Account')),
                ('contract_code', models.ManyToManyField(to='bank.Contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
