# Generated by Django 3.1.1 on 2020-10-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201024_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
