# Generated by Django 3.1.1 on 2020-10-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20201024_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
    ]
