# Generated by Django 3.1.1 on 2020-10-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('report', models.TextField(max_length=540)),
            ],
        ),
    ]
