# Generated by Django 3.0.5 on 2020-10-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='min_date',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='min_sum',
        ),
    ]
