# Generated by Django 3.0.3 on 2020-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
