# Generated by Django 3.0.3 on 2020-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20200606_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
