# Generated by Django 3.1.2 on 2020-10-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshow', '0003_brandlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brandlist',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.DeleteModel(
            name='Masterlist',
        ),
        migrations.DeleteModel(
            name='Masters',
        ),
        migrations.DeleteModel(
            name='Pricelist',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
        migrations.DeleteModel(
            name='Workshops',
        ),
        migrations.DeleteModel(
            name='Workslist',
        ),
    ]
