# Generated by Django 3.1.2 on 2020-10-02 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=20)),
                ('car_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rent_price', models.FloatField()),
                ('min_car_price', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='image',
            field=models.ImageField(upload_to='pic_users'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_datetime', models.DateTimeField()),
                ('return_datetime', models.DateTimeField()),
                ('actual_return_datetime', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carclass'),
        ),
    ]
