# Generated by Django 3.1.2 on 2020-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_pickuppoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sits_number',
            field=models.IntegerField(default=5),
        ),
    ]
