# Generated by Django 3.1.2 on 2020-10-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_sits_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='pic_cars'),
        ),
        migrations.AddField(
            model_name='rent',
            name='return_to',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='return_to', to='cars.pickuppoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='taken_from',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='taken_from', to='cars.pickuppoint'),
            preserve_default=False,
        ),
    ]
