# Generated by Django 3.1.2 on 2020-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201002_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='actual_return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
