# Generated by Django 3.0.6 on 2020-06-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_auto_20200622_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_code',
        ),
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.Client'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_order',
            field=models.DateField(auto_now_add=True),
        ),
    ]
