# Generated by Django 3.0.6 on 2020-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_auto_20200623_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant_app.Dishes'),
        ),
    ]
