# Generated by Django 3.1.2 on 2020-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='description',
            field=models.TimeField(),
        ),
    ]
