# Generated by Django 3.1.2 on 2020-10-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201014_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='description',
            field=models.TextField(),
        ),
    ]
