# Generated by Django 3.1.2 on 2020-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201014_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='sing',
            field=models.CharField(max_length=50),
        ),
    ]
