# Generated by Django 3.1.2 on 2020-10-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201014_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='type',
        ),
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disk',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
