# Generated by Django 3.1.2 on 2020-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201016_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='price',
        ),
        migrations.AlterField(
            model_name='disk',
            name='price',
            field=models.IntegerField(),
        ),
    ]
