# Generated by Django 3.0.5 on 2020-09-10 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attraction', models.CharField(max_length=45)),
                ('year_purchase', models.IntegerField()),
                ('old', models.IntegerField()),
                ('adult_price', models.IntegerField()),
                ('children_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AttractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_playground', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Use_attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('adult_ticket', models.IntegerField(default=0)),
                ('children_ticket', models.IntegerField(default=0)),
                ('attraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useAttraction', to='core.Attraction')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useAttraction', to='core.Playground')),
            ],
        ),
        migrations.CreateModel(
            name='My_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_purchase', to='core.Attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attraction', to='core.AttractionType'),
        ),
    ]
