# Generated by Django 3.0.5 on 2020-09-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_purchase',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
