# Generated by Django 3.1.2 on 2020-11-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izdat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('category_code', models.CharField(max_length=45)),
                ('number_of_pages', models.IntegerField()),
                ('year_of_publication', models.DateField()),
                ('isbn_kode', models.IntegerField()),
                ('author_has_book', models.ManyToManyField(to='izdat_app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('phone_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Book_has_Order', models.ManyToManyField(to='izdat_app.Book')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izdat_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_of_copies', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='izdat_app.book')),
            ],
        ),
    ]
