# Generated by Django 3.1.2 on 2020-11-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izdat_app', '0003_auto_20201101_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
