# Generated by Django 3.0.7 on 2020-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
