# Generated by Django 3.0.7 on 2020-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200628_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
