# Generated by Django 3.0.7 on 2020-06-28 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_driver_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='bio',
        ),
        migrations.AddField(
            model_name='bus',
            name='brand',
            field=models.CharField(default='MAN', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='birth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='hiring_date',
            field=models.DateField(auto_now_add=True, default='2000-4-21'),
            preserve_default=False,
        ),
    ]
