# Generated by Django 3.0.7 on 2020-06-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200628_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birth',
            field=models.DateField(default='1980-05-24'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='hiring_date',
            field=models.DateField(default='2020-01-12'),
        ),
    ]
