# Generated by Django 3.0.7 on 2020-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200628_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_datetime',
            field=models.DateTimeField(),
        ),
    ]
