# Generated by Django 3.0.3 on 2020-02-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('dateo', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('passportnum', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vodud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='datebuy')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exmamople_app.User')),
            ],
        ),
    ]
