# Generated by Django 3.0.3 on 2020-02-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exmamople_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mej',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyd', models.DateField()),
                ('selld', models.DateField()),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exmamople_app.Avtom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exmamople_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dates',
            field=models.ManyToManyField(through='exmamople_app.Mej', to='exmamople_app.Avtom'),
        ),
    ]
