# Generated by Django 3.0.3 on 2020-02-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exmamople_app', '0002_auto_20200211_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passportnum',
            field=models.IntegerField(),
        ),
    ]
