# Generated by Django 3.0.7 on 2020-06-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сassette',
            name='duration',
            field=models.TimeField(),
        ),
    ]
