# Generated by Django 3.0.7 on 2020-06-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_auto_20200621_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_cassette', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_shop.Сassette')),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_shop.Seller')),
            ],
        ),
    ]
