# Generated by Django 3.0.7 on 2020-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_auto_20200621_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='id_cassette',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='id_seller',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='selling',
            name='id_cassette',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='selling',
            name='id_profile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='selling',
            name='id_seller',
            field=models.IntegerField(),
        ),
    ]
