# Generated by Django 3.0.7 on 2020-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comppubhouse_app', '0003_auto_20200627_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
