# Generated by Django 3.0.7 on 2020-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comppubhouse_app', '0004_order_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='in_orders',
            field=models.ManyToManyField(through='comppubhouse_app.BooksInOrder', to='comppubhouse_app.Order'),
        ),
    ]
