# Generated by Django 3.0.7 on 2020-06-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comppubhouse_app', '0005_auto_20200627_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(null=True),
        ),
    ]
