# Generated by Django 3.0.4 on 2020-03-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.CharField(choices=[('BMW', 'Bayerische Motoren Werke AG'), ('Volvo', 'Volvo'), ('Peugot', 'Peugot'), ('VAZ', 'Russian Automobile')], max_length=10)),
                ('Model', models.CharField(max_length=25)),
                ('Color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Blue', 'Blue')], max_length=10)),
                ('Number', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('CarInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Car')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Person')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('DateOfCreate', models.DateField()),
                ('Type', models.CharField(choices=[('A', 'Motorcycle'), ('B', 'Easyweight'), ('C', 'Heavyweight'), ('D', 'Bus'), ('M', 'Quadrocycles')], max_length=15)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.Person')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='member',
            field=models.ManyToManyField(related_name='Owner', to='project_first_app.Person'),
        ),
    ]
