# Generated by Django 3.0.4 on 2020-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_auto_20200325_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='ID',
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
