# Generated by Django 3.0.4 on 2020-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0006_auto_20200325_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='member',
            field=models.ManyToManyField(through='project_first_app.Owner', to='project_first_app.Person'),
        ),
    ]
