# Generated by Django 3.0.4 on 2020-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0007_car_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='member',
        ),
        migrations.AddField(
            model_name='person',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.Owner', to='project_first_app.Car'),
        ),
    ]
