# Generated by Django 3.0.4 on 2020-03-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('state_number', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Have_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateField()),
                ('date_sale', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makhotkin_app.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('cars', models.ManyToManyField(through='makhotkin_app.Have_car', to='makhotkin_app.Car')),
            ],
        ),
        migrations.AddField(
            model_name='have_car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makhotkin_app.Owner'),
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('date_issued', models.DateField()),
                ('type', models.CharField(choices=[('S', 'Standart'), ('I', 'International')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makhotkin_app.Owner')),
            ],
        ),
    ]
