# Generated by Django 3.0.8 on 2020-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('theme', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('translate', models.CharField(max_length=50)),
                ('film_studio', models.CharField(max_length=50)),
                ('poster', models.TextField()),
                ('number_group', models.CharField(max_length=10)),
                ('number_of_student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ManyToManyField(to='app.Book')),
                ('reader', models.ManyToManyField(to='app.Reader')),
            ],
        ),
    ]
