# Generated by Django 3.1.1 on 2020-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='games',
            field=models.ManyToManyField(related_name='discs', to='Gameshop.Game', verbose_name='Игры'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='genres',
            field=models.ManyToManyField(related_name='discs', to='Gameshop.Genre', verbose_name='Жанры'),
        ),
    ]
