# Generated by Django 3.0.5 on 2020-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attraction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
