# Generated by Django 3.0.3 on 2020-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20200605_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='fuel_type',
            field=models.IntegerField(choices=[(1, 'Бензин'), (2, 'Дизельное топливо'), (3, 'Природный газ'), (4, 'Электриество')]),
        ),
    ]
