# Generated by Django 3.0.6 on 2020-05-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_zone_code', models.IntegerField(default=0)),
                ('call_zone_code', models.IntegerField(default=0)),
                ('call_price_per_minute', models.IntegerField(default=0)),
                ('user_zone_name', models.CharField(max_length=50)),
                ('call_zone_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('telephone_number', models.IntegerField(default=0)),
                ('cash_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CashInformation')),
            ],
        ),
        migrations.CreateModel(
            name='UserCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=0)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CallInformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='callinformation',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Rate'),
        ),
        migrations.AddField(
            model_name='callinformation',
            name='users',
            field=models.ManyToManyField(through='myapp.UserCall', to='myapp.User'),
        ),
    ]
