# Generated by Django 3.0.6 on 2020-05-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200528_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercall',
            name='pay_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
