# Generated by Django 3.0.6 on 2020-05-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200528_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
