# Generated by Django 3.0.6 on 2020-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Login',
            field=models.SlugField(max_length=20),
        ),
    ]
