# Generated by Django 3.0.6 on 2020-05-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200528_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='User',
            new_name='user',
        ),
    ]
